service: aws-abla-docker-cicd

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, 'prod'}
  region: ${env:AWS_REGION, 'us-east-1'}
  ecr:
    images:
      img:
        path: ./
        platform: linux/amd64

custom:
  pythonRequirements:
    dockerizePip: true

functions:
  dev:
    timeout: 60
    memorySize: 2048
    image:
      name: img
    events:
      - http:
          path: /lenovoSorted
          method: get
